// This file is auto-generated by oagen. Do not edit.

mod common;

use sellapp::Error;
use wiremock::matchers::{method, path as path_matcher};
use wiremock::{Mock, MockServer, ResponseTemplate};

#[tokio::test]
async fn blacklists_list_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_list_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .list(sellapp::resources::blacklists::ListParams::default())
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_list_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .list(sellapp::resources::blacklists::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_list_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .list(sellapp::resources::blacklists::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_list_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .list(sellapp::resources::blacklists::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_list_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .list(sellapp::resources::blacklists::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_list_empty_page() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{\"data\":[],\"links\":{\"first\":\"https://sell.app/api/v1/blacklists?page=1\",\"last\":\"https://sell.app/api/v1/blacklists?page=4\",\"prev\":\"test_prev\",\"next\":\"https://sell.app/api/v1/blacklists?page=2\"},\"meta\":{\"current_page\":1,\"from\":1,\"last_page\":4,\"links\":[{\"url\":\"test_url\",\"label\":\"test_label\",\"active\":false}],\"path\":\"https://sell.app/api/v1/blacklists\",\"per_page\":15,\"to\":15,\"total\":57}}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let resp = client
        .blacklists()
        .list(sellapp::resources::blacklists::ListParams::default())
        .await
        .expect("expected success");
    assert!(resp.data.is_empty(), "expected empty data array");
}

#[tokio::test]
async fn blacklists_create_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_create_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_create_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_create_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_create_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_create_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_create_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v1/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .create(sellapp::resources::blacklists::CreateParams::new(
            serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                .expect("parse fixture for BlacklistCreateRequest"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn blacklists_get_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .get("test_id")
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_get_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .get("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_get_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .get("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_get_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .get("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_get_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .get("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_update_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_update_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_update_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_update_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_update_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_update_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_update_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .update(
            "test_id",
            sellapp::resources::blacklists::UpdateParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn blacklists_delete_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .delete("test_id")
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_delete_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .delete("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_delete_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .delete("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_delete_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .delete("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_delete_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .delete("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_delete_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .delete("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_delete_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v1/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .delete("test_id")
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn blacklists_v_2_list_blacklists_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_list_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .v_2_list_blacklists(sellapp::resources::blacklists::V2ListBlacklistsParams::default())
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_v_2_list_blacklists_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_list_blacklists(sellapp::resources::blacklists::V2ListBlacklistsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_v_2_list_blacklists_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_list_blacklists(sellapp::resources::blacklists::V2ListBlacklistsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_v_2_list_blacklists_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_list_blacklists(sellapp::resources::blacklists::V2ListBlacklistsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_v_2_list_blacklists_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_list_blacklists(sellapp::resources::blacklists::V2ListBlacklistsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_v_2_list_blacklists_empty_page() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{\"data\":[],\"links\":{\"first\":\"https://sell.app/api/v1/blacklists?page=1\",\"last\":\"https://sell.app/api/v1/blacklists?page=4\",\"prev\":\"test_prev\",\"next\":\"https://sell.app/api/v1/blacklists?page=2\"},\"meta\":{\"current_page\":1,\"from\":1,\"last_page\":4,\"links\":[{\"url\":\"test_url\",\"label\":\"test_label\",\"active\":false}],\"path\":\"https://sell.app/api/v1/blacklists\",\"per_page\":15,\"to\":15,\"total\":57}}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let resp = client
        .blacklists()
        .v_2_list_blacklists(sellapp::resources::blacklists::V2ListBlacklistsParams::default())
        .await
        .expect("expected success");
    assert!(resp.data.is_empty(), "expected empty data array");
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_v_2_create_blacklist_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/blacklists"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_create_blacklist(
            sellapp::resources::blacklists::V2CreateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_create_request.json"))
                    .expect("parse fixture for BlacklistCreateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn blacklists_v_2_get_blacklist_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .v_2_get_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2GetBlacklistParams::default(),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_v_2_get_blacklist_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_get_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2GetBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_v_2_get_blacklist_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_get_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2GetBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_v_2_get_blacklist_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_get_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2GetBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_v_2_get_blacklist_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_get_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2GetBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_v_2_replace_blacklist_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("PUT"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_replace_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2ReplaceBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_v_2_update_blacklist_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_update_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2UpdateBlacklistParams::new(
                serde_json::from_str(include_str!("fixtures/blacklist_update_request.json"))
                    .expect("parse fixture for BlacklistUpdateRequest"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/blacklist_response.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn blacklists_v_2_delete_blacklist_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("DELETE"))
        .and(path_matcher("/v2/blacklists/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .blacklists()
        .v_2_delete_blacklist(
            "test_id",
            sellapp::resources::blacklists::V2DeleteBlacklistParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}
