// This file is auto-generated by oagen. Do not edit.

mod common;

use sellapp::Error;
use wiremock::matchers::{method, path as path_matcher};
use wiremock::{Mock, MockServer, ResponseTemplate};

#[tokio::test]
async fn bookings_list_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .bookings()
        .list(sellapp::resources::bookings::ListParams::default())
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn bookings_list_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .list(sellapp::resources::bookings::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn bookings_list_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .list(sellapp::resources::bookings::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn bookings_list_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .list(sellapp::resources::bookings::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn bookings_list_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .list(sellapp::resources::bookings::ListParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn bookings_search_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn bookings_search_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn bookings_search_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn bookings_search_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn bookings_search_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn bookings_search_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn bookings_search_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/bookings/search"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .search(sellapp::resources::bookings::SearchParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_search_appointments_request_application_json.json"
            ))
            .expect("parse fixture for SdkSearchAppointmentsRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn bookings_get_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_get_appointment_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .bookings()
        .get(
            "test_id",
            sellapp::resources::bookings::GetParams::default(),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn bookings_get_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .get(
            "test_id",
            sellapp::resources::bookings::GetParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn bookings_get_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .get(
            "test_id",
            sellapp::resources::bookings::GetParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn bookings_get_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .get(
            "test_id",
            sellapp::resources::bookings::GetParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn bookings_get_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .get(
            "test_id",
            sellapp::resources::bookings::GetParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn bookings_update_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_update_appointment_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn bookings_update_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn bookings_update_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn bookings_update_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn bookings_update_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn bookings_update_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn bookings_update_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .update(
            "test_id",
            sellapp::resources::bookings::UpdateParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_update_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkUpdateAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn bookings_cancel_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_cancel_appointment_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn bookings_cancel_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn bookings_cancel_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn bookings_cancel_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn bookings_cancel_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn bookings_cancel_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn bookings_cancel_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("PATCH"))
        .and(path_matcher("/v2/bookings/test_id/status"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .bookings()
        .cancel(
            "test_id",
            sellapp::resources::bookings::CancelParams::new(
                serde_json::from_str(include_str!(
                    "fixtures/sdk_cancel_appointment_request_application_json.json"
                ))
                .expect("parse fixture for SdkCancelAppointmentRequestApplicationJson"),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}
