// This file is auto-generated by oagen. Do not edit.

mod common;

use sellapp::Error;
use wiremock::matchers::{method, path as path_matcher};
use wiremock::{Mock, MockServer, ResponseTemplate};

#[tokio::test]
async fn events_list_integration_events_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/events"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_list_integration_events_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .events()
        .list_integration_events(sellapp::resources::events::ListIntegrationEventsParams::default())
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn events_list_integration_events_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_integration_events(sellapp::resources::events::ListIntegrationEventsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn events_list_integration_events_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_integration_events(sellapp::resources::events::ListIntegrationEventsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn events_list_integration_events_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_integration_events(sellapp::resources::events::ListIntegrationEventsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn events_list_integration_events_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_integration_events(sellapp::resources::events::ListIntegrationEventsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn events_list_integration_events_empty_page() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/events"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{\"data\":[],\"meta\":{\"next_cursor\":\"test_next_cursor\",\"has_more\":false,\"retention_days\":30}}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let resp = client
        .events()
        .list_integration_events(sellapp::resources::events::ListIntegrationEventsParams::default())
        .await
        .expect("expected success");
    assert!(resp.data.is_empty(), "expected empty data array");
}

#[tokio::test]
async fn events_list_order_events_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/orders/test_id/events"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_list_order_events_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .events()
        .list_order_events(
            "test_id",
            sellapp::resources::events::ListOrderEventsParams::default(),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn events_list_order_events_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/orders/test_id/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_order_events(
            "test_id",
            sellapp::resources::events::ListOrderEventsParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn events_list_order_events_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/orders/test_id/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_order_events(
            "test_id",
            sellapp::resources::events::ListOrderEventsParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn events_list_order_events_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/orders/test_id/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_order_events(
            "test_id",
            sellapp::resources::events::ListOrderEventsParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn events_list_order_events_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/orders/test_id/events"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .events()
        .list_order_events(
            "test_id",
            sellapp::resources::events::ListOrderEventsParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn events_list_order_events_empty_page() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/orders/test_id/events"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{\"data\":[],\"meta\":{\"next_cursor\":\"test_next_cursor\",\"has_more\":false,\"retention_days\":30}}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let resp = client
        .events()
        .list_order_events(
            "test_id",
            sellapp::resources::events::ListOrderEventsParams::default(),
        )
        .await
        .expect("expected success");
    assert!(resp.data.is_empty(), "expected empty data array");
}
