// This file is auto-generated by oagen. Do not edit.

mod common;

use sellapp::Error;
use wiremock::matchers::{method, path as path_matcher};
use wiremock::{Mock, MockServer, ResponseTemplate};

#[tokio::test]
async fn exports_list_exports_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_list_exports_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .exports()
        .list_exports(sellapp::resources::exports::ListExportsParams::default())
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn exports_list_exports_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .list_exports(sellapp::resources::exports::ListExportsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn exports_list_exports_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .list_exports(sellapp::resources::exports::ListExportsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn exports_list_exports_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .list_exports(sellapp::resources::exports::ListExportsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn exports_list_exports_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .list_exports(sellapp::resources::exports::ListExportsParams::default())
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn exports_list_exports_empty_page() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{\"data\":[],\"links\":{\"first\":\"https://sell.app/api/v1/blacklists?page=1\",\"last\":\"https://sell.app/api/v1/blacklists?page=4\",\"prev\":\"test_prev\",\"next\":\"https://sell.app/api/v1/blacklists?page=2\"},\"meta\":{\"current_page\":1,\"from\":1,\"last_page\":4,\"links\":[{\"url\":\"test_url\",\"label\":\"test_label\",\"active\":false}],\"path\":\"https://sell.app/api/v1/blacklists\",\"per_page\":15,\"to\":15,\"total\":57}}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let resp = client
        .exports()
        .list_exports(sellapp::resources::exports::ListExportsParams::default())
        .await
        .expect("expected success");
    assert!(resp.data.is_empty(), "expected empty data array");
}

#[tokio::test]
async fn exports_create_export_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_create_export_response_value_201_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn exports_create_export_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn exports_create_export_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn exports_create_export_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn exports_create_export_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn exports_create_export_bad_request() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(400)
        .set_body_string("{\"code\":\"validation_error\",\"message\":\"Bad request\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 400);
    assert_eq!(api.code.as_deref(), Some("validation_error"));
}

#[tokio::test]
async fn exports_create_export_unprocessable() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(422).set_body_string("{\"message\":\"Unprocessable\"}");
    Mock::given(method("POST"))
        .and(path_matcher("/v2/exports"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .create_export(sellapp::resources::exports::CreateExportParams::new(
            serde_json::from_str(include_str!(
                "fixtures/sdk_create_export_request_application_json.json"
            ))
            .expect("parse fixture for SdkCreateExportRequestApplicationJson"),
        ))
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 422);
}

#[tokio::test]
async fn exports_get_export_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id"))
        .respond_with(ResponseTemplate::new(200).set_body_string(include_str!(
            "fixtures/sdk_get_export_response_value_200_application_json.json"
        )))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .exports()
        .get_export(
            "test_id",
            sellapp::resources::exports::GetExportParams::default(),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn exports_get_export_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .get_export(
            "test_id",
            sellapp::resources::exports::GetExportParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn exports_get_export_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .get_export(
            "test_id",
            sellapp::resources::exports::GetExportParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn exports_get_export_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .get_export(
            "test_id",
            sellapp::resources::exports::GetExportParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn exports_get_export_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .get_export(
            "test_id",
            sellapp::resources::exports::GetExportParams::default(),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}

#[tokio::test]
async fn exports_download_export_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id/download"))
        .respond_with(ResponseTemplate::new(200).set_body_string("null"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    client
        .exports()
        .download_export(
            "test_id",
            sellapp::resources::exports::DownloadExportParams::new(
                serde_json::from_str("0").expect("parse stub"),
                "test_signature".to_string(),
            ),
        )
        .await
        .expect("valid generated response");
}

#[tokio::test]
async fn exports_download_export_unauthorized() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(401).set_body_string("{\"message\":\"Unauthorized\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id/download"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .download_export(
            "test_id",
            sellapp::resources::exports::DownloadExportParams::new(
                serde_json::from_str("0").expect("parse stub"),
                "test_signature".to_string(),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Authentication(api) => api.as_ref(),
        other => panic!("expected Error::Authentication, got {other:?}"),
    };
    assert_eq!(api.status, 401);
}

#[tokio::test]
async fn exports_download_export_not_found() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(404).set_body_string("{\"message\":\"Not found\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id/download"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .download_export(
            "test_id",
            sellapp::resources::exports::DownloadExportParams::new(
                serde_json::from_str("0").expect("parse stub"),
                "test_signature".to_string(),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 404);
}

#[tokio::test]
async fn exports_download_export_rate_limited() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(429)
        .insert_header("retry-after", "1")
        .set_body_string("{\"message\":\"Slow down\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id/download"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .download_export(
            "test_id",
            sellapp::resources::exports::DownloadExportParams::new(
                serde_json::from_str("0").expect("parse stub"),
                "test_signature".to_string(),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 429);
    assert_eq!(api.retry_after, Some(std::time::Duration::from_secs(1)));
}

#[tokio::test]
async fn exports_download_export_server_error() {
    let server = MockServer::start().await;
    let template = ResponseTemplate::new(500).set_body_string("{\"message\":\"Internal error\"}");
    Mock::given(method("GET"))
        .and(path_matcher("/v2/exports/test_id/download"))
        .respond_with(template)
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let err = client
        .exports()
        .download_export(
            "test_id",
            sellapp::resources::exports::DownloadExportParams::new(
                serde_json::from_str("0").expect("parse stub"),
                "test_signature".to_string(),
            ),
        )
        .await
        .expect_err("expected error");
    let api = match &err {
        Error::Api(api) => api.as_ref(),
        other => panic!("expected Error::Api, got {other:?}"),
    };
    assert_eq!(api.status, 500);
}
