// This file is auto-generated by oagen. Do not edit.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    TopUp,
    TopUpBonus,
    Cashback,
    CashbackClawback,
    TopUpClawback,
    Reward,
    Refund,
    PurchaseDebit,
    ManualAdjustment,
    Reversal,
    Expiration,
    /// Wire value not recognized by this SDK version. The original
    /// string is preserved verbatim. SellApp may add new enum values
    /// server-side; matching on this variant lets callers handle
    /// forward-compatible values without panicking.
    Unknown(String),
}

impl ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    /// Canonical wire string for this value. For [`Self::Unknown`] returns the
    /// original wire value as received from the API.
    #[allow(deprecated)]
    pub fn as_str(&self) -> &str {
        match self {
            Self::TopUp => "TOP_UP",
            Self::TopUpBonus => "TOP_UP_BONUS",
            Self::Cashback => "CASHBACK",
            Self::CashbackClawback => "CASHBACK_CLAWBACK",
            Self::TopUpClawback => "TOP_UP_CLAWBACK",
            Self::Reward => "REWARD",
            Self::Refund => "REFUND",
            Self::PurchaseDebit => "PURCHASE_DEBIT",
            Self::ManualAdjustment => "MANUAL_ADJUSTMENT",
            Self::Reversal => "REVERSAL",
            Self::Expiration => "EXPIRATION",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Whether this value was declared by the schema used to generate the SDK.
    pub fn is_known(&self) -> bool {
        !matches!(self, Self::Unknown(_))
    }
}

impl fmt::Display for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl AsRef<str> for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl FromStr for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    type Err = std::convert::Infallible;
    #[allow(deprecated)]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            "TOP_UP" => Self::TopUp,
            "TOP_UP_BONUS" => Self::TopUpBonus,
            "CASHBACK" => Self::Cashback,
            "CASHBACK_CLAWBACK" => Self::CashbackClawback,
            "TOP_UP_CLAWBACK" => Self::TopUpClawback,
            "REWARD" => Self::Reward,
            "REFUND" => Self::Refund,
            "PURCHASE_DEBIT" => Self::PurchaseDebit,
            "MANUAL_ADJUSTMENT" => Self::ManualAdjustment,
            "REVERSAL" => Self::Reversal,
            "EXPIRATION" => Self::Expiration,
            other => Self::Unknown(other.to_string()),
        })
    }
}

impl From<String> for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    fn from(s: String) -> Self {
        // Reuse the original `String` allocation in the fallback branch.
        match Self::from_str(&s) {
            Ok(Self::Unknown(_)) => Self::Unknown(s),
            Ok(other) => other,
        }
    }
}

impl From<&str> for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    fn from(s: &str) -> Self {
        Self::from_str(s).unwrap_or_else(|_| Self::Unknown(s.to_string()))
    }
}

impl Serialize for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de>
    for ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItemType
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}
