// This file is auto-generated by oagen. Do not edit.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    Id,
    Email,
    ExternalId,
    Locale,
    /// Wire value not recognized by this SDK version. The original
    /// string is preserved verbatim. SellApp may add new enum values
    /// server-side; matching on this variant lets callers handle
    /// forward-compatible values without panicking.
    Unknown(String),
}

impl SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    /// Canonical wire string for this value. For [`Self::Unknown`] returns the
    /// original wire value as received from the API.
    #[allow(deprecated)]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Id => "id",
            Self::Email => "email",
            Self::ExternalId => "external_id",
            Self::Locale => "locale",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Whether this value was declared by the schema used to generate the SDK.
    pub fn is_known(&self) -> bool {
        !matches!(self, Self::Unknown(_))
    }
}

impl fmt::Display for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl AsRef<str> for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl FromStr for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    type Err = std::convert::Infallible;
    #[allow(deprecated)]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            "id" => Self::Id,
            "email" => Self::Email,
            "external_id" => Self::ExternalId,
            "locale" => Self::Locale,
            other => Self::Unknown(other.to_string()),
        })
    }
}

impl From<String> for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    fn from(s: String) -> Self {
        // Reuse the original `String` allocation in the fallback branch.
        match Self::from_str(&s) {
            Ok(Self::Unknown(_)) => Self::Unknown(s),
            Ok(other) => other,
        }
    }
}

impl From<&str> for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    fn from(s: &str) -> Self {
        Self::from_str(s).unwrap_or_else(|_| Self::Unknown(s.to_string()))
    }
}

impl Serialize for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for SearchCustomersRequestApplicationJsonPropertyFiltersItemField {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}
