// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem {
    #[serde(rename = "type")]
    pub type_: BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItemType,
    pub required: bool,
    pub label: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub options: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub placeholder: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub variant: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub date_options: Option<BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItemPropertyDateOptions>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> { Self::serialize(self, serializer) }
}
impl<'de> Deserialize<'de> for BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(&value, "BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem", false).map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(&mut value, "BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem");
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self).map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(&value, "BatchUpdateProductsRequestApplicationJsonPropertyResourcesMapValuePropertyAdditionalInformationItem", true)
    }
}
