// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData {
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub stock: Option<Option<i64>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub serials: Option<Vec<String>>,
    #[serde(rename = "removeDuplicate")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub remove_duplicate: Option<bool>,
    #[serde(rename = "parsingMode")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub parsing_mode: Option<CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataParsingMode>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub comment: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub webhook: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub booking: Option<CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyBooking>,
    /// Tiered unit prices for credit products. Credit products must include at least one priced tier.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub credit_rate_tiers: Option<Vec<CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyDataPropertyCreditRateTiersItem>>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "CreateProductVariantRequestApplicationJsonPropertyDeliverablePropertyData",
            true,
        )
    }
}
