// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice {
    pub id: i64,
    pub payment: CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyPayment,
    pub status: CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyStatus,
    pub webhooks: Vec<CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyWebhooksItem>,
    pub feedback: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub store_id: i64,
    pub coupon_id: Option<i64>,
    pub subscription_id: Option<i64>,
    pub customer_information: CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyCustomerInformation,
    pub product_variants: Vec<CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoicePropertyProductVariantsItem>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice",
            true,
        )
    }
}
