// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem {
    pub id: i64,
    #[serde(rename = "type")]
    pub type_: IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType,
    pub payload: IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemPropertyPayload,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub coupon_id: Option<Option<i64>>,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub wallet_ledger_entry_id: Option<Option<i64>>,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub created_at: Option<Option<String>>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize
    for IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem
{
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(&value, "IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem", false).map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "IssueEligibleRewardGrantResponseValue201ApplicationJsonPropertyDataPropertyOutputsItem",
            true,
        )
    }
}
