// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem {
    pub id: i64,
    pub affiliate_id: i64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub affiliate_email: Option<String>,
    pub amount_usd_cents: i64,
    pub status: ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItemStatus,
    #[serde(
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "crate::runtime_schema::present_nullable"
    )]
    pub payout_method: Option<Option<String>>,
    /// A masked payout destination. Full payout credentials are never returned.
    pub payout_account: String,
    pub referrals_count: i64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub created_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub updated_at: Option<String>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de> for ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem",
            true,
        )
    }
}
