// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem {
    pub id: i64,
    pub store_id: i64,
    pub customer_id: i64,
    pub product_id: i64,
    pub kind: ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItemKind,
    pub amount_units: i64,
    pub balance_after_units: i64,
    pub idempotency_key: String,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub source_type: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub source_id: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub reason: Option<Option<String>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItemPropertyMetadata>,
    #[serde(skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::runtime_schema::present_nullable")]
    pub actor_user_id: Option<Option<i64>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub created_at: Option<String>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem",
            true,
        )
    }
}
