// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData {
    pub product_id: i64,
    pub product_variant_id: i64,
    pub mode: String,
    pub conflict_scope: ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope,
    pub timezone: String,
    pub duration_minutes: i64,
    pub capacity_per_slot: i64,
    pub min_notice_minutes: i64,
    pub max_advance_days: i64,
    pub buffer_before_minutes: i64,
    pub buffer_after_minutes: i64,
    pub availability: Vec<ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem>,
    pub provider_connection_ids: Vec<i64>,
    pub video_provider: ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataVideoProvider,
    pub video_provider_connection_id: Option<i64>,
    pub reminders_enabled: bool,
    pub reminder_offset_value: i64,
    pub reminder_offset_unit: ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit,
    pub meta: ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyMeta,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData",
            true,
        )
    }
}
