// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct SdkV2SearchFeedbackRequestApplicationJson {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filters: Option<Vec<V2SearchFeedbackRequestApplicationJsonPropertyFiltersItem>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sort: Option<Vec<V2SearchFeedbackRequestApplicationJsonPropertySortItem>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub search: Option<V2SearchFeedbackRequestApplicationJsonPropertySearch>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub includes: Option<Vec<V2SearchFeedbackRequestApplicationJsonPropertyIncludesItem>>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for SdkV2SearchFeedbackRequestApplicationJson {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de> for SdkV2SearchFeedbackRequestApplicationJson {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(&value, "SdkV2SearchFeedbackRequestApplicationJson", false)
            .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "SdkV2SearchFeedbackRequestApplicationJson",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl SdkV2SearchFeedbackRequestApplicationJson {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(&value, "SdkV2SearchFeedbackRequestApplicationJson", true)
    }
}
