// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct SdkUpdateProductVariantRequestApplicationJson {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub deliverable: Option<UpdateProductVariantRequestApplicationJsonPropertyDeliverable>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub pricing: Option<UpdateProductVariantRequestApplicationJsonPropertyPricing>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub minimum_purchase_quantity: Option<i64>,
    #[serde(
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "crate::runtime_schema::present_nullable"
    )]
    pub maximum_purchase_quantity: Option<Option<i64>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub bulk_discount:
        Option<Vec<UpdateProductVariantRequestApplicationJsonPropertyBulkDiscountItem>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub payment_methods: Option<Vec<SdkUpdateProductVariantRequestApplicationJsonPaymentMethods>>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub other_settings: Option<UpdateProductVariantRequestApplicationJsonPropertyOtherSettings>,
    /// Optional optimistic-concurrency snapshot for updates. Use the variant's latest updated_at value; stale snapshots receive a 422 validation response.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expected_updated_at: Option<String>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for SdkUpdateProductVariantRequestApplicationJson {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de> for SdkUpdateProductVariantRequestApplicationJson {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "SdkUpdateProductVariantRequestApplicationJson",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "SdkUpdateProductVariantRequestApplicationJson",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl SdkUpdateProductVariantRequestApplicationJson {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "SdkUpdateProductVariantRequestApplicationJson",
            true,
        )
    }
}
