// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The product identity and title snapshot captured when the line item was created. The ID is null when the referenced product cannot be verified as belonging to the authenticated store; same-store soft-deleted products retain their ID for historical reporting.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct {
    pub id: Option<i64>,
    pub title: Option<String>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize
    for SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct
{
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyProduct",
            true,
        )
    }
}
