// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// A privacy-bounded customer summary. IP address, browser fingerprint, billing details, and community identities are intentionally omitted.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer
{
    pub id: Option<i64>,
    pub email: Option<String>,
    pub country: Option<String>,
    pub location: Option<String>,
    pub proxied: Option<bool>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize
    for SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer
{
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(&value, "SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer", false).map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyCustomer",
            true,
        )
    }
}
