// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct UpdateAppointmentResponseValue200ApplicationJsonPropertyData {
    pub id: String,
    pub product_id: i64,
    pub product_variant_id: i64,
    pub order_id: i64,
    pub invoice_id: i64,
    pub customer_id: Option<i64>,
    pub customer_email: Option<String>,
    pub slot_start_at: String,
    pub slot_end_at: String,
    pub timezone: String,
    pub quantity: i64,
    pub status: UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus,
    pub calendar_sync_status:
        UpdateAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus,
    /// Calendar event URL. Always null after cancellation.
    pub external_event_link: Option<String>,
    /// Video meeting URL. Always null after cancellation.
    pub video_join_url: Option<String>,
    pub confirmed_at: Option<String>,
    pub cancelled_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub product:
        Option<UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct>,
    pub variant:
        Option<UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for UpdateAppointmentResponseValue200ApplicationJsonPropertyData {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de> for UpdateAppointmentResponseValue200ApplicationJsonPropertyData {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "UpdateAppointmentResponseValue200ApplicationJsonPropertyData",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "UpdateAppointmentResponseValue200ApplicationJsonPropertyData",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl UpdateAppointmentResponseValue200ApplicationJsonPropertyData {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "UpdateAppointmentResponseValue200ApplicationJsonPropertyData",
            true,
        )
    }
}
