// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing {
    pub humble: bool,
    pub frequency: UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyFrequency,
    #[serde(rename = "type")]
    pub type_: String,
    pub price: UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyPrice,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "UpdateProductVariantResponseValue200ApplicationJsonPropertyDataPropertyPricing",
            true,
        )
    }
}
