// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(remote = "Self")]
pub struct UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights {
    pub orders_count: i64,
    pub line_items_count: i64,
    pub completed_line_items_count: i64,
    pub pending_line_items_count: i64,
    pub voided_line_items_count: i64,
    pub subscriptions_count: i64,
    /// Completed line-item revenue in integer USD minor units.
    pub revenue_usd_cents: i64,
    pub first_purchase_at: Option<String>,
    pub last_purchase_at: Option<String>,
    /// The most frequently used line-item payment method.
    pub favorite_payment_method: Option<String>,
    /// Fields returned by a newer API version that are not yet known to this SDK.
    #[serde(default, flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
impl Serialize for UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Self::serialize(self, serializer)
    }
}
impl<'de> Deserialize<'de>
    for UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights
{
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut value = serde_json::Value::deserialize(deserializer)?;
        crate::runtime_schema::model(
            &value,
            "UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights",
            false,
        )
        .map_err(serde::de::Error::custom)?;
        crate::runtime_schema::retain_model_fields(
            &mut value,
            "UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights",
        );
        Self::deserialize(value).map_err(serde::de::Error::custom)
    }
}
impl UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights {
    /// Validate the serialized request, including schema constraints and compatibility rules.
    pub fn validate_request(&self) -> Result<(), crate::error::Error> {
        let value = serde_json::to_value(self)
            .map_err(|e| crate::error::Error::Serialization(e.to_string()))?;
        crate::runtime_schema::model(
            &value,
            "UpsertCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights",
            true,
        )
    }
}
