// This file is auto-generated by oagen. Do not edit.

pub mod client;
pub mod enums;
pub mod error;
pub mod models;
pub mod pagination;
pub mod resources;
mod resources_api;
mod runtime_schema;
pub use client::{
    BodyEncoding, Client, LifecycleEvent, LifecyclePhase, MultipartFile, RawResponse,
    RequestOptions,
};
pub use error::{ApiError, Error};
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub struct SecretString(String);
impl From<String> for SecretString {
    fn from(v: String) -> Self {
        Self(v)
    }
}
impl From<&str> for SecretString {
    fn from(v: &str) -> Self {
        Self(v.to_string())
    }
}
impl std::fmt::Debug for SecretString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("[REDACTED]")
    }
}
